version: "3.8"

services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ZOOKEEPER_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092
      ALLOW_PLAINTEXT_LISTENER: yes

    depends_on:
       - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

  producer_service:
    build:
      context: ./producer/producer
    container_name: producer
    ports:
       - "8080:8080"
    depends_on:
      - kafka

  consumer_service:
    build:
      context: ./consumer/consumer
    container_name: consumer
    ports:
      - "8081:8081"
    depends_on:
      - kafka
